Update to Spacy 3.0, update Pyphen
sloev/spacy-syllables pull request #1
Opened 2021-03-03 22:58 UTC by nikitalita

This updates to use the new custom component system that Spacy 3.0 uses (`@Language.factory`) with attributes. 

I also updated to pyphen 0.10. Because it no longer has the same defaults for languages without country codes as it does before, I added those as defaults for spacy-syllables.

2021-03-04 11:23 UTC, sloev requested changes
Hey thanks for a PR!!! :-)
all in all it looks great! 
some minor changes are requested.
when fixed i will release as a major version update since we drop support for spacy 2.x i guess (which is fine!)

2021-03-04 11:23 UTC, sloev commented on spacy_syllables/__init__.py
> +        elif lang == "en":
lets use the pyphen.language_fallback function to get a short or localized lang code from the given one instead:
https://github.com/Kozea/Pyphen/blob/4e3cac0c90d80ceb2d6209575a1b46cb812fe4b1/pyphen/__init__.py#L53

2021-03-04 11:23 UTC, sloev commented on spacy_syllables/__init__.py
> +            lang = "en_US"
pyphen supports a ton of languages, locking ourselves to this shortlist is unnecesary

2021-03-04 11:23 UTC, sloev commented on spacy_syllables/__init__.py
> +    def __init__(self, nlp: Language, name: str = "syllables", lang: Optional[str] = None):
lang should be before name, its more common to set the language than the name i think
and name: str should propably be name: Optional[str] = "syllables"

2021-03-04 18:00 UTC, nikitalita commented on spacy_syllables/__init__.py
> +    def __init__(self, nlp: Language, name: str = "syllables", lang: Optional[str] = None):
The way you add Spacy 3.0 pipeline components means that this init will never be called by the user; custom configuration information gets set in the add_pipe, i.e. `nlp.add_pipe("syllables", after="tagger", config={"lang": "en_US"})`. The way the parameters are laid out here seems to be the convention for spacy 3.0 pipeline components, but I don't think it matters too much, if you still want me to change it, I will.

2021-03-04 18:06 UTC, nikitalita commented on spacy_syllables/__init__.py
> +        elif lang == "en":
I originally did exactly this. The problem is that this resulted in changed behavior. For example, `hyph_en.dic` used to be a soft-link to `en_US`, but it was removed in Pyphen 0.10.0, and the fallback now defaults to `en_GB`. This resulted in failed tests, with certain words having changed numbers of syllables.

2021-03-04 18:07 UTC, nikitalita commented on spacy_syllables/__init__.py
> +            lang = "en_US"
This is only a workaround for the removal of the symlinked defaults in pyphen for the listed languages here, to avoid changing our default behavior. If there's a country code, or if it's not one of these languages, this section won't get called.

2021-03-04 18:34 UTC, nikitalita commented
I've just added a section to the readme with information on how to migrate the module spacy 2.x to 3.0, to head off any confusion here. If you don't think it's necessary, I'll remove it.

2021-03-04 18:51 UTC, nikitalita commented on spacy_syllables/__init__.py
> +            lang = "en_US"
Just so you can see what I'm talking about, `ls` from pyphen-0.9.5:

```
hyph_de.dic -> hyph_de_DE.dic         
hyph_de_AT.dic                        
hyph_de_CH.dic                        
hyph_de_DE.dic                        
hyph_el.dic -> hyph_el_GR.dic         
hyph_el_GR.dic                        
hyph_en.dic -> hyph_en_US.dic         
hyph_en_GB.dic                        
hyph_en_Latn_GB.dic -> hyph_en_GB.dic 
hyph_en_Latn_US.dic -> hyph_en_US.dic 
hyph_en_US.dic                        
[...]
hyph_pt.dic -> hyph_pt_PT.dic         
hyph_pt_BR.dic                        
hyph_pt_Latn_BR.dic -> hyph_pt_BR.dic 
hyph_pt_Latn_PT.dic -> hyph_pt_PT.dic 
hyph_pt_PT.dic                        
```

The defaults for `de`, `en`, and `pt` changed as a result of dropping the symlinks, because `pyphen.language_fallback()` just looks up alphabetically. So, `de` defaults to `de_AT` instead of `de_DE`, `en` defaults to `en_GB` instead of `en_US`, and `pt` defaults to `pt_BR` instead of `pt_PT`.

While other languages had their symlinked defaults dropped (like `hyph_el.dic -> hyph_el_GR.dic`), these only had one country variation, so it was not necessary to add those to the workaround.

2021-03-05 08:23 UTC, sloev approved these changes
all your replies show how much outdated i am with spacy. Thanks for clarification!!!
i will get this out asap

2021-03-05 08:24 UTC, merged

2021-03-05 08:48 UTC, sloev commented
@nikitalita spacy-syllables 3.0.1 has been released
thanks for the great work!